server:
  port: 8402
spring:
  application:
    name: eureka-server
eureka:
  instance:
    #eureka.instance.prefer-ip-address=true eureka.instance.ip-address=172.12.9.0这两个参数配合使用 可以转移服务访问的ip
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8402/eureka/,http://localhost:8401/eureka/
  server:
    #等待同步时间 毫秒
    wait-time-in-ms-when-sync-empty: 10000
    #自动保护模式
#    enable-self-preservation: false